import { useState, useEffect, useCallback } from "react";
import {
  Building2, BookOpen, Users, ChevronRight, Plus, X,
  FileText, Github, Download, Trash2, GraduationCap,
  ExternalLink, Save, Pencil, Check, BarChart2, ClipboardList,
  Edit2, Camera, Loader2, RefreshCw, Search, AlertCircle,
  Wifi, WifiOff, Home, LogOut, User, Mail, Phone, MapPin,
  Calendar, Award, TrendingUp, Settings, Menu
} from "lucide-react";
import { supabase, isSupabaseAvailable } from './lib/supabase';

// ── Types ─────────────────────────────────────────────────────────────────────
type View = "schools" | "classes" | "students" | "student" | "docs";
type Term = 1 | 2 | 3;
type AType = "test1" | "test2" | "test3" | "project" | "exam";
type Grade = "A+" | "A" | "B" | "C" | "D" | "F";

interface School {
  id: string; name: string; address: string;
  principal: string; email: string; phone: string; color: string;
  created_at?: string;
}
interface Klass {
  id: string; schoolId: string; name: string; teacher: string; subject: string;
  academicYear: string; created_at?: string;
}
interface Student {
  id: string; classId: string; firstName: string; lastName: string;
  email: string; github: string; avatar?: string;
  phone?: string; address?: string; dateOfBirth?: string;
  guardianName?: string; guardianPhone?: string; created_at?: string;
}
interface Asmt {
  id: string; studentId: string; term: Term; type: AType; score: number; max: number;
  year: string; created_at?: string;
}
interface Doc {
  id: string; schoolId: string; classId: string | null;
  term: Term; type: AType; title: string; content: string; createdAt: string;
  year: string; created_at?: string;
}

// ── Constants ─────────────────────────────────────────────────────────────────
const CURRENT_YEAR = "2024-2025";
const TL: Record<Term, string> = { 1: "First Term", 2: "Second Term", 3: "Third Term" };
const AL: Record<AType, string> = { 
  test1: "Test 1", test2: "Test 2", test3: "Test 3", 
  project: "Project", exam: "Final Exam" 
};
const AMAX: Record<AType, number> = { test1: 30, test2: 30, test3: 30, project: 50, exam: 100 };
const ATYPES: AType[] = ["test1", "test2", "test3", "project", "exam"];

const GRADE_COLORS: Record<Grade, string> = {
  "A+": "text-emerald-600 bg-emerald-50",
  "A": "text-emerald-600 bg-emerald-50",
  "B": "text-blue-600 bg-blue-50",
  "C": "text-amber-600 bg-amber-50",
  "D": "text-orange-600 bg-orange-50",
  "F": "text-red-600 bg-red-50",
};

// ── Utils ──────────────────────────────────────────────────────────────────────
let _n = 9000;
const uid = () => String(++_n);
const today = () => new Date().toISOString().slice(0, 10);

const pct = (s: number, m: number) => Math.round((s / m) * 100);
const gradeStr = (s: number, m: number): Grade => {
  const p = pct(s, m);
  return p >= 90 ? "A+" : p >= 80 ? "A" : p >= 70 ? "B" : p >= 60 ? "C" : p >= 50 ? "D" : "F";
};
const avgPct = (asmts: Asmt[]) =>
  asmts.length ? Math.round(asmts.reduce((sum, a) => sum + pct(a.score, a.max), 0) / asmts.length) : null;

const badgeCls = (s: number, m: number) => {
  const p = pct(s, m);
  return p >= 80 ? "bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200"
    : p >= 60 ? "bg-amber-50 text-amber-700 ring-1 ring-amber-200"
    : "bg-red-50 text-red-700 ring-1 ring-red-200";
};
const barCls = (s: number, m: number) => {
  const p = pct(s, m);
  return p >= 80 ? "bg-emerald-500" : p >= 60 ? "bg-amber-500" : "bg-red-500";
};

const inputCls = "w-full border border-gray-200 rounded-lg px-4 py-2.5 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all placeholder:text-gray-400";
const labelCls = "text-xs font-semibold text-gray-700 mb-1.5 block uppercase tracking-wide";

function dlDoc(doc: Doc) {
  const sep = "─".repeat(60);
  const txt = [
    doc.title, "=".repeat(60), "",
    `${AL[doc.type]}  |  ${TL[doc.term]}  |  Created: ${doc.createdAt}`,
    "", sep, "", doc.content, "", sep, "Generated by SchoolTrack — Academic Document System",
  ].join("\n");
  const a = Object.assign(document.createElement("a"), {
    href: URL.createObjectURL(new Blob([txt], { type: "text/plain" })),
    download: `${doc.title.replace(/\W+/g, "_")}.txt`,
  });
  a.click();
}

// ── Avatar Component ──────────────────────────────────────────────────────────
function Avatar({ student, size = "md", editable = false, onUpload }: { 
  student: Student; 
  size?: "sm" | "md" | "lg" | "xl";
  editable?: boolean;
  onUpload?: (file: File) => void;
}) {
  const sizes = { sm: "w-8 h-8 text-xs", md: "w-12 h-12 text-sm", lg: "w-16 h-16 text-lg", xl: "w-24 h-24 text-2xl" };
  const [isHovering, setIsHovering] = useState(false);
  const initials = `${student.firstName[0]}${student.lastName[0]}`.toUpperCase();

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file && onUpload) onUpload(file);
  };

  return (
    <div 
      className="relative inline-block"
      onMouseEnter={() => setIsHovering(true)}
      onMouseLeave={() => setIsHovering(false)}
    >
      <div className={`${sizes[size]} rounded-full flex items-center justify-center font-bold text-white flex-shrink-0 overflow-hidden bg-gradient-to-br from-blue-600 to-purple-600 shadow-md`}>
        {student.avatar ? (
          <img src={student.avatar} alt={initials} className="w-full h-full object-cover" />
        ) : initials}
      </div>
      {editable && (
        <label className={`absolute inset-0 rounded-full cursor-pointer flex items-center justify-center bg-black/50 transition-opacity ${isHovering ? 'opacity-100' : 'opacity-0'}`}>
          <Camera size={size === "sm" ? 12 : size === "md" ? 16 : 20} className="text-white" />
          <input type="file" accept="image/*" className="hidden" onChange={handleFileChange} />
        </label>
      )}
    </div>
  );
}

// ── Modals ──────────────────────────────────────────────────────────────────

function AddSchoolModal({ onSave, onClose }: { onSave: (s: School) => void; onClose: () => void }) {
  const [f, setF] = useState({ name: "", address: "", principal: "", email: "", phone: "", color: "#3b82f6" });
  const COLORS = ["#3b82f6", "#10b981", "#8b5cf6", "#f59e0b", "#ef4444", "#ec4899", "#14b8a6", "#f97316"];
  const set = (k: keyof typeof f) => (e: React.ChangeEvent<HTMLInputElement>) => setF(p => ({ ...p, [k]: e.target.value }));

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md animate-in fade-in zoom-in duration-200">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <h2 className="font-bold text-lg text-gray-900">Add New School</h2>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg transition-colors"><X size={18} /></button>
        </div>
        <div className="px-6 py-6 space-y-4">
          <div>
            <label className={labelCls}>School Name *</label>
            <input value={f.name} onChange={set("name")} placeholder="e.g. Greenfield Academy" className={inputCls} />
          </div>
          <div>
            <label className={labelCls}>Address</label>
            <input value={f.address} onChange={set("address")} placeholder="14 Oak Lane, Springfield" className={inputCls} />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className={labelCls}>Principal</label>
              <input value={f.principal} onChange={set("principal")} placeholder="Dr. Name" className={inputCls} />
            </div>
            <div>
              <label className={labelCls}>Phone</label>
              <input value={f.phone} onChange={set("phone")} placeholder="+1 555-0000" className={inputCls} />
            </div>
          </div>
          <div>
            <label className={labelCls}>Email</label>
            <input value={f.email} onChange={set("email")} type="email" placeholder="info@school.edu" className={inputCls} />
          </div>
          <div>
            <label className={labelCls}>School Colour</label>
            <div className="flex gap-2.5 flex-wrap mt-1">
              {COLORS.map(c => (
                <button key={c} onClick={() => setF(p => ({ ...p, color: c }))}
                  className="w-9 h-9 rounded-full transition-all hover:scale-110"
                  style={{ background: c, boxShadow: f.color === c ? `0 0 0 3px white, 0 0 0 5px ${c}` : undefined }}
                />
              ))}
            </div>
          </div>
        </div>
        <div className="flex gap-3 px-6 pb-6">
          <button onClick={onClose} className="flex-1 py-2.5 border border-gray-200 rounded-xl text-sm font-medium hover:bg-gray-50 transition-colors">Cancel</button>
          <button onClick={() => { if (!f.name.trim()) return; onSave({ id: uid(), ...f }); onClose(); }}
            className="flex-1 py-2.5 bg-blue-600 text-white rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors shadow-sm">
            Save School
          </button>
        </div>
      </div>
    </div>
  );
}

function AddClassModal({ schoolId, onSave, onClose }: { schoolId: string; onSave: (k: Klass) => void; onClose: () => void }) {
  const [f, setF] = useState({ name: "", teacher: "", subject: "", academicYear: CURRENT_YEAR });
  const set = (k: keyof typeof f) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setF(p => ({ ...p, [k]: e.target.value }));
  const years = ["2023-2024", "2024-2025", "2025-2026"];

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm animate-in fade-in zoom-in duration-200">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <h2 className="font-bold text-lg text-gray-900">Add New Class</h2>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg"><X size={18} /></button>
        </div>
        <div className="px-6 py-6 space-y-4">
          <div>
            <label className={labelCls}>Class Name *</label>
            <input value={f.name} onChange={set("name")} placeholder="e.g. Grade 10A" className={inputCls} />
          </div>
          <div>
            <label className={labelCls}>Subject</label>
            <input value={f.subject} onChange={set("subject")} placeholder="e.g. Mathematics" className={inputCls} />
          </div>
          <div>
            <label className={labelCls}>Class Teacher</label>
            <input value={f.teacher} onChange={set("teacher")} placeholder="Ms. Name" className={inputCls} />
          </div>
          <div>
            <label className={labelCls}>Academic Year</label>
            <select value={f.academicYear} onChange={set("academicYear")} className={inputCls}>
              {years.map(y => <option key={y} value={y}>{y}</option>)}
            </select>
          </div>
        </div>
        <div className="flex gap-3 px-6 pb-6">
          <button onClick={onClose} className="flex-1 py-2.5 border border-gray-200 rounded-xl text-sm font-medium hover:bg-gray-50">Cancel</button>
          <button onClick={() => { if (!f.name.trim()) return; onSave({ id: uid(), schoolId, ...f }); onClose(); }}
            className="flex-1 py-2.5 bg-blue-600 text-white rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors">
            Save Class
          </button>
        </div>
      </div>
    </div>
  );
}

function AddStudentModal({ classId, onSave, onClose }: { classId: string; onSave: (s: Student) => void; onClose: () => void }) {
  const [f, setF] = useState({ firstName: "", lastName: "", email: "", github: "", phone: "", address: "" });
  const set = (k: keyof typeof f) => (e: React.ChangeEvent<HTMLInputElement>) => setF(p => ({ ...p, [k]: e.target.value }));

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm animate-in fade-in zoom-in duration-200">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <h2 className="font-bold text-lg text-gray-900">Add New Student</h2>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg"><X size={18} /></button>
        </div>
        <div className="px-6 py-6 space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className={labelCls}>First Name *</label>
              <input value={f.firstName} onChange={set("firstName")} placeholder="Kofi" className={inputCls} />
            </div>
            <div>
              <label className={labelCls}>Last Name *</label>
              <input value={f.lastName} onChange={set("lastName")} placeholder="Mensah" className={inputCls} />
            </div>
          </div>
          <div>
            <label className={labelCls}>Email</label>
            <input value={f.email} onChange={set("email")} type="email" placeholder="student@school.edu" className={inputCls} />
          </div>
          <div>
            <label className={labelCls}>GitHub Username</label>
            <input value={f.github} onChange={set("github")} placeholder="github-username" className={inputCls} />
          </div>
          <div>
            <label className={labelCls}>Phone</label>
            <input value={f.phone} onChange={set("phone")} placeholder="+233 20 123 4567" className={inputCls} />
          </div>
          <div>
            <label className={labelCls}>Address</label>
            <input value={f.address} onChange={set("address")} placeholder="City, Country" className={inputCls} />
          </div>
        </div>
        <div className="flex gap-3 px-6 pb-6">
          <button onClick={onClose} className="flex-1 py-2.5 border border-gray-200 rounded-xl text-sm font-medium hover:bg-gray-50">Cancel</button>
          <button onClick={() => { if (!f.firstName.trim()) return; onSave({ id: uid(), classId, ...f }); onClose(); }}
            className="flex-1 py-2.5 bg-blue-600 text-white rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors">
            Add Student
          </button>
        </div>
      </div>
    </div>
  );
}

function EditProfileModal({ student, onSave, onClose }: { student: Student; onSave: (s: Student) => void; onClose: () => void }) {
  const [f, setF] = useState(student);
  const set = (k: keyof Student) => (e: React.ChangeEvent<HTMLInputElement>) => setF(p => ({ ...p, [k]: e.target.value }));

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md max-h-[90vh] overflow-y-auto animate-in fade-in zoom-in duration-200">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 sticky top-0 bg-white z-10">
          <h2 className="font-bold text-lg text-gray-900">Edit Profile</h2>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg"><X size={18} /></button>
        </div>
        <div className="px-6 py-6 space-y-4">
          <div className="flex justify-center mb-4"><Avatar student={f} size="xl" editable={false} /></div>
          <div className="grid grid-cols-2 gap-3">
            <div><label className={labelCls}>First Name *</label><input value={f.firstName} onChange={set("firstName")} className={inputCls} /></div>
            <div><label className={labelCls}>Last Name *</label><input value={f.lastName} onChange={set("lastName")} className={inputCls} /></div>
          </div>
          <div><label className={labelCls}>Email</label><input value={f.email} onChange={set("email")} type="email" className={inputCls} /></div>
          <div><label className={labelCls}>GitHub Username</label><input value={f.github} onChange={set("github")} className={inputCls} /></div>
          <div><label className={labelCls}>Phone</label><input value={f.phone || ""} onChange={set("phone")} className={inputCls} /></div>
          <div><label className={labelCls}>Address</label><input value={f.address || ""} onChange={set("address")} className={inputCls} /></div>
          <div><label className={labelCls}>Date of Birth</label><input value={f.dateOfBirth || ""} onChange={set("dateOfBirth")} type="date" className={inputCls} /></div>
          <div><label className={labelCls}>Guardian Name</label><input value={f.guardianName || ""} onChange={set("guardianName")} className={inputCls} /></div>
          <div><label className={labelCls}>Guardian Phone</label><input value={f.guardianPhone || ""} onChange={set("guardianPhone")} className={inputCls} /></div>
        </div>
        <div className="flex gap-3 px-6 pb-6 sticky bottom-0 bg-white pt-4 border-t border-gray-100">
          <button onClick={onClose} className="flex-1 py-2.5 border border-gray-200 rounded-xl text-sm font-medium hover:bg-gray-50">Cancel</button>
          <button onClick={() => { onSave(f); onClose(); }}
            className="flex-1 py-2.5 bg-blue-600 text-white rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors">
            Save Changes
          </button>
        </div>
      </div>
    </div>
  );
}

function AddDocModal({ schools, klasses, onSave, onClose }: { schools: School[]; klasses: Klass[]; onSave: (d: Doc) => void; onClose: () => void }) {
  const [f, setF] = useState({ schoolId: "", classId: "", term: "1", type: "exam" as AType, title: "", content: "", year: CURRENT_YEAR });
  const filteredK = klasses.filter(k => k.schoolId === f.schoolId);
  const years = ["2023-2024", "2024-2025", "2025-2026"];
  const setS = (k: keyof typeof f) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) =>
    setF(p => ({ ...p, [k]: e.target.value }));

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[92vh] flex flex-col animate-in fade-in zoom-in duration-200">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 flex-shrink-0">
          <h2 className="font-bold text-lg text-gray-900">Create Document</h2>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg"><X size={18} /></button>
        </div>
        <div className="px-6 py-6 space-y-4 overflow-y-auto flex-1">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className={labelCls}>School *</label>
              <select value={f.schoolId} onChange={setS("schoolId")} className={inputCls}>
                <option value="">— Select school —</option>
                {schools.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
            </div>
            <div>
              <label className={labelCls}>Class</label>
              <select value={f.classId} onChange={setS("classId")} disabled={!f.schoolId} className={inputCls + " disabled:opacity-50"}>
                <option value="">— Select class —</option>
                {filteredK.map(k => <option key={k.id} value={k.id}>{k.name}</option>)}
              </select>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className={labelCls}>Term</label>
              <select value={f.term} onChange={setS("term")} className={inputCls}>
                <option value="1">First Term</option>
                <option value="2">Second Term</option>
                <option value="3">Third Term</option>
              </select>
            </div>
            <div>
              <label className={labelCls}>Type</label>
              <select value={f.type} onChange={setS("type")} className={inputCls}>
                {ATYPES.map(t => <option key={t} value={t}>{AL[t]}</option>)}
              </select>
            </div>
          </div>
          <div>
            <label className={labelCls}>Academic Year</label>
            <select value={f.year} onChange={setS("year")} className={inputCls}>
              {years.map(y => <option key={y} value={y}>{y}</option>)}
            </select>
          </div>
          <div>
            <label className={labelCls}>Document Title *</label>
            <input value={f.title} onChange={setS("title")} placeholder="e.g. Grade 10A First Term Exam" className={inputCls} />
          </div>
          <div>
            <label className={labelCls}>Questions / Content</label>
            <textarea value={f.content} onChange={setS("content")} rows={10}
              className="w-full border border-gray-200 rounded-xl px-4 py-3 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono resize-none" />
          </div>
        </div>
        <div className="flex gap-3 px-6 pb-6 border-t border-gray-100 pt-4 flex-shrink-0">
          <button onClick={onClose} className="flex-1 py-2.5 border border-gray-200 rounded-xl text-sm font-medium hover:bg-gray-50">Cancel</button>
          <button onClick={() => { if (!f.title.trim() || !f.schoolId) return; onSave({ id: uid(), schoolId: f.schoolId, classId: f.classId || null, term: Number(f.term) as Term, type: f.type, title: f.title, content: f.content, createdAt: today(), year: f.year }); onClose(); }}
            className="flex-1 py-2.5 bg-blue-600 text-white rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors">
            Create Document
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Views ────────────────────────────────────────────────────────────────────

function SchoolsView({ schools, onOpen, onAdd, onDelete }: { schools: School[]; onOpen: (s: School) => void; onAdd: () => void; onDelete: (id: string) => void }) {
  return (
    <div className="p-6 max-w-7xl mx-auto w-full">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-8 gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Schools</h1>
          <p className="text-sm text-gray-500 mt-1">{schools.length} registered {schools.length === 1 ? "school" : "schools"}</p>
        </div>
        <button onClick={onAdd} className="flex items-center gap-2 bg-blue-600 text-white px-5 py-2.5 rounded-xl text-sm font-semibold hover:bg-blue-700 transition-all shadow-sm hover:shadow-md">
          <Plus size={18} /> Add School
        </button>
      </div>
      {schools.length === 0 ? (
        <div className="text-center py-16 bg-gray-50 rounded-2xl border-2 border-dashed border-gray-200">
          <Building2 size={48} className="mx-auto mb-4 text-gray-300" />
          <p className="text-gray-600 font-medium">No schools yet</p>
          <p className="text-sm text-gray-400 mt-1">Add your first school to get started</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {schools.map(school => (
            <div key={school.id} className="bg-white rounded-2xl border border-gray-200 overflow-hidden hover:shadow-lg transition-all group">
              <div className="h-1.5" style={{ background: school.color }} />
              <div className="p-6">
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-3 min-w-0">
                    <div className="w-12 h-12 rounded-xl flex items-center justify-center text-white text-lg font-bold flex-shrink-0 shadow-sm" style={{ background: school.color }}>
                      {school.name.split(" ").map(w => w[0]).slice(0, 2).join("")}
                    </div>
                    <div className="min-w-0">
                      <h3 className="font-bold text-gray-900 truncate">{school.name}</h3>
                      <p className="text-xs text-gray-500 truncate">{school.principal}</p>
                    </div>
                  </div>
                  <button onClick={() => onDelete(school.id)} className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg opacity-0 group-hover:opacity-100 transition-all">
                    <Trash2 size={16} />
                  </button>
                </div>
                <p className="text-sm text-gray-500 mb-4 line-clamp-2">{school.address}</p>
                <div className="text-xs text-gray-400 space-y-1">
                  <div className="truncate">{school.email}</div>
                  <div>{school.phone}</div>
                </div>
                <button onClick={() => onOpen(school)} className="mt-4 w-full flex items-center justify-center gap-2 text-sm font-semibold py-2.5 rounded-xl transition-all border border-gray-200 hover:bg-blue-600 hover:text-white hover:border-blue-600">
                  View Classes <ChevronRight size={16} />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function ClassesView({ school, klasses, students, onOpen, onAdd, onBack, onDelete }: { school: School; klasses: Klass[]; students: Student[]; onOpen: (k: Klass) => void; onAdd: () => void; onBack: () => void; onDelete: (id: string) => void }) {
  return (
    <div className="p-6 max-w-7xl mx-auto w-full">
      <nav className="flex items-center gap-2 text-sm text-gray-500 mb-6">
        <button onClick={onBack} className="hover:text-gray-700 transition-colors">Schools</button>
        <ChevronRight size={14} />
        <span className="text-gray-900 font-semibold">{school.name}</span>
      </nav>
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-8 gap-4">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl flex items-center justify-center text-white text-lg font-bold flex-shrink-0 shadow-sm" style={{ background: school.color }}>
            {school.name.split(" ").map(w => w[0]).slice(0, 2).join("")}
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">{school.name}</h1>
            <p className="text-sm text-gray-500">{klasses.length} {klasses.length === 1 ? "class" : "classes"} · {school.principal}</p>
          </div>
        </div>
        <button onClick={onAdd} className="flex items-center gap-2 bg-blue-600 text-white px-5 py-2.5 rounded-xl text-sm font-semibold hover:bg-blue-700 transition-all shadow-sm hover:shadow-md">
          <Plus size={18} /> Add Class
        </button>
      </div>
      {klasses.length === 0 ? (
        <div className="text-center py-16 bg-gray-50 rounded-2xl border-2 border-dashed border-gray-200">
          <BookOpen size={48} className="mx-auto mb-4 text-gray-300" />
          <p className="text-gray-600 font-medium">No classes yet</p>
          <p className="text-sm text-gray-400 mt-1">Add the first class to this school</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {klasses.map(k => {
            const count = students.filter(s => s.classId === k.id).length;
            return (
              <div key={k.id} className="bg-white rounded-2xl border border-gray-200 p-6 hover:shadow-md transition-all group">
                <div className="flex items-start justify-between mb-4">
                  <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center">
                    <BookOpen size={18} className="text-blue-600" />
                  </div>
                  <button onClick={() => onDelete(k.id)} className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg opacity-0 group-hover:opacity-100 transition-all">
                    <Trash2 size={16} />
                  </button>
                </div>
                <h3 className="font-bold text-gray-900">{k.name}</h3>
                <p className="text-sm text-gray-500">{k.subject}</p>
                <p className="text-sm text-gray-500">{k.teacher}</p>
                <p className="text-xs text-gray-400 mt-2 font-mono">{k.academicYear}</p>
                <div className="flex items-center justify-between mt-4 pt-4 border-t border-gray-100">
                  <span className="text-sm bg-gray-100 text-gray-600 px-3 py-1 rounded-full font-medium">
                    {count} {count !== 1 ? "students" : "student"}
                  </span>
                  <button onClick={() => onOpen(k)} className="flex items-center gap-1 text-sm font-semibold text-blue-600 hover:text-blue-700">
                    View Students <ChevronRight size={14} />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

function StudentsView({ school, klass, students, asmts, onOpen, onAdd, onBack, onBackSchool, onDelete }: { school: School; klass: Klass; students: Student[]; asmts: Asmt[]; onOpen: (s: Student) => void; onAdd: () => void; onBack: () => void; onBackSchool: () => void; onDelete: (id: string) => void }) {
  const [search, setSearch] = useState("");
  const filteredStudents = students.filter(s => 
    `${s.firstName} ${s.lastName}`.toLowerCase().includes(search.toLowerCase()) || 
    s.email?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="p-6 max-w-7xl mx-auto w-full">
      <nav className="flex items-center gap-2 text-sm text-gray-500 mb-6 flex-wrap">
        <button onClick={onBackSchool} className="hover:text-gray-700 transition-colors">Schools</button>
        <ChevronRight size={14} />
        <button onClick={onBack} className="hover:text-gray-700 transition-colors">{school.name}</button>
        <ChevronRight size={14} />
        <span className="text-gray-900 font-semibold">{klass.name}</span>
      </nav>
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-6 gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">{klass.name}</h1>
          <p className="text-sm text-gray-500">{klass.subject} · {klass.teacher} · {students.length} {students.length === 1 ? "student" : "students"}</p>
        </div>
        <button onClick={onAdd} className="flex items-center gap-2 bg-blue-600 text-white px-5 py-2.5 rounded-xl text-sm font-semibold hover:bg-blue-700 transition-all shadow-sm hover:shadow-md">
          <Plus size={18} /> Add Student
        </button>
      </div>
      
      <div className="relative mb-6">
        <Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
        <input 
          value={search} 
          onChange={e => setSearch(e.target.value)} 
          placeholder="Search students by name or email..." 
          className="w-full pl-11 pr-4 py-3 border border-gray-200 rounded-xl text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" 
        />
      </div>

      {filteredStudents.length === 0 ? (
        <div className="text-center py-16 bg-gray-50 rounded-2xl border-2 border-dashed border-gray-200">
          <Users size={48} className="mx-auto mb-4 text-gray-300" />
          <p className="text-gray-600 font-medium">No students found</p>
          <p className="text-sm text-gray-400 mt-1">{students.length > 0 ? "Try adjusting your search" : "Add the first student to this class"}</p>
        </div>
      ) : (
        <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-200 bg-gray-50">
                  <th className="text-left px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Student</th>
                  <th className="text-left px-4 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider hidden md:table-cell">Email</th>
                  <th className="text-left px-4 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider hidden lg:table-cell">GitHub</th>
                  <th className="text-left px-4 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Avg</th>
                  <th className="px-4 py-4"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {filteredStudents.map(st => {
                  const stAsmts = asmts.filter(a => a.studentId === st.id && a.year === klass.academicYear);
                  const avg = avgPct(stAsmts);
                  return (
                    <tr key={st.id} className="hover:bg-gray-50 transition-colors group">
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-3">
                          <Avatar student={st} size="sm" />
                          <span className="font-semibold text-gray-900">{st.firstName} {st.lastName}</span>
                        </div>
                      </td>
                      <td className="px-4 py-4 text-gray-500 text-sm hidden md:table-cell">{st.email}</td>
                      <td className="px-4 py-4 hidden lg:table-cell">
                        {st.github && (
                          <a href={`https://github.com/${st.github}`} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-700 transition-colors">
                            <Github size={14} />
                            <span>{st.github}</span>
                          </a>
                        )}
                      </td>
                      <td className="px-4 py-4">
                        {avg !== null && (
                          <span className={`text-sm font-bold px-3 py-1 rounded-full ${avg >= 80 ? "bg-emerald-50 text-emerald-700" : avg >= 60 ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}>
                            {avg}%
                          </span>
                        )}
                      </td>
                      <td className="px-4 py-4 text-right">
                        <div className="flex items-center justify-end gap-2">
                          <button onClick={() => onDelete(st.id)} className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg opacity-0 group-hover:opacity-100 transition-all">
                            <Trash2 size={16} />
                          </button>
                          <button onClick={() => onOpen(st)} className="px-4 py-1.5 text-sm font-semibold text-blue-600 border border-blue-200 rounded-lg hover:bg-blue-600 hover:text-white hover:border-blue-600 transition-all">
                            View Profile
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}

function StudentDetailView({ 
  school, klass, student, asmts, onUpdateScore, onBack, onBackClass, onBackSchool, onUpdateStudent 
}: { 
  school: School; klass: Klass; student: Student; asmts: Asmt[]; 
  onUpdateScore: (id: string, score: number) => void; 
  onBack: () => void; onBackClass: () => void; onBackSchool: () => void; 
  onUpdateStudent: (s: Student) => void;
}) {
  const [term, setTerm] = useState<Term>(1);
  const [editId, setEditId] = useState<string | null>(null);
  const [editVal, setEditVal] = useState("");
  const [showEditProfile, setShowEditProfile] = useState(false);
  const [selectedYear, setSelectedYear] = useState(CURRENT_YEAR);

  const termAsmts = asmts.filter(a => a.term === term && a.year === selectedYear);
  const getAsmt = (t: AType) => termAsmts.find(a => a.type === t);
  const overall = avgPct(asmts.filter(a => a.year === selectedYear));
  const termAvg = avgPct(termAsmts);
  const yearAsmts = asmts.filter(a => a.year === selectedYear);
  const termGrades: { term: Term; grade: Grade; percentage: number; year: string }[] = [1, 2, 3].map(t => {
    const tAsmts = yearAsmts.filter(a => a.term === t);
    const p = avgPct(tAsmts);
    return { term: t as Term, grade: p !== null ? gradeStr(p, 100) : "F", percentage: p || 0, year: selectedYear };
  });
  const years = Array.from(new Set(asmts.map(a => a.year))).sort();
  const typeIcons: Record<AType, React.ReactNode> = { 
    test1: <ClipboardList size={16} />, test2: <ClipboardList size={16} />, 
    test3: <ClipboardList size={16} />, project: <GraduationCap size={16} />, 
    exam: <BarChart2 size={16} /> 
  };

  const commitEdit = (a: Asmt) => {
    const v = parseFloat(editVal);
    if (!isNaN(v) && v >= 0 && v <= a.max) onUpdateScore(a.id, Math.round(v));
    setEditId(null);
  };

  const handleAvatarUpload = (file: File) => {
    const reader = new FileReader();
    reader.onload = e => onUpdateStudent({ ...student, avatar: e.target?.result as string });
    reader.readAsDataURL(file);
  };

  return (
    <div className="p-6 max-w-5xl mx-auto w-full">
      <nav className="flex items-center gap-2 text-sm text-gray-500 mb-6 flex-wrap">
        <button onClick={onBackSchool} className="hover:text-gray-700 transition-colors">Schools</button>
        <ChevronRight size={14} />
        <button onClick={onBack} className="hover:text-gray-700 transition-colors">{school.name}</button>
        <ChevronRight size={14} />
        <button onClick={onBackClass} className="hover:text-gray-700 transition-colors">{klass.name}</button>
        <ChevronRight size={14} />
        <span className="text-gray-900 font-semibold truncate">{student.firstName} {student.lastName}</span>
      </nav>

      <div className="bg-white rounded-2xl border border-gray-200 p-6 mb-6 shadow-sm">
        <div className="flex flex-col md:flex-row items-start md:items-center gap-6">
          <div className="flex items-center gap-5 w-full md:w-auto">
            <Avatar student={student} size="lg" editable onUpload={handleAvatarUpload} />
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-3 flex-wrap">
                <h1 className="text-2xl font-bold text-gray-900 truncate">{student.firstName} {student.lastName}</h1>
                <button onClick={() => setShowEditProfile(true)} className="p-1.5 hover:bg-gray-100 rounded-lg transition-colors">
                  <Edit2 size={16} className="text-gray-500" />
                </button>
              </div>
              <p className="text-sm text-gray-500">{klass.name} · {klass.subject} · {school.name}</p>
              <div className="flex flex-wrap items-center gap-4 mt-2">
                <span className="text-sm text-gray-500 font-mono">{student.email}</span>
                {student.github && (
                  <a href={`https://github.com/${student.github}`} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-700 transition-colors">
                    <Github size={14} />
                    <span>{student.github}</span>
                    <ExternalLink size={12} />
                  </a>
                )}
              </div>
            </div>
          </div>
          {overall !== null && (
            <div className="text-right flex-shrink-0 w-full md:w-auto">
              <div className={`text-3xl font-bold font-mono ${overall >= 80 ? "text-emerald-600" : overall >= 60 ? "text-amber-600" : "text-red-600"}`}>
                {overall}%
              </div>
              <div className="text-sm text-gray-500 mt-0.5">Overall Average</div>
            </div>
          )}
        </div>
        <div className="mt-6 pt-6 border-t border-gray-100">
          <div className="flex flex-wrap items-center gap-4">
            <label className="text-sm font-semibold text-gray-700">Academic Year:</label>
            <select 
              value={selectedYear} 
              onChange={e => setSelectedYear(e.target.value)} 
              className="border border-gray-200 rounded-lg px-4 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              {years.length > 0 ? years.map(y => <option key={y} value={y}>{y}</option>) : <option value={CURRENT_YEAR}>{CURRENT_YEAR}</option>}
            </select>
          </div>
        </div>
      </div>

      <div className="flex gap-1 mb-6 bg-gray-100 rounded-xl p-1 w-fit">
        {([1, 2, 3] as Term[]).map(t => {
          const grade = termGrades.find(tg => tg.term === t);
          return (
            <button 
              key={t} 
              onClick={() => setTerm(t)} 
              className={`px-5 py-2.5 rounded-lg text-sm font-semibold transition-all flex items-center gap-2 ${term === t ? "bg-white shadow-sm text-gray-900" : "text-gray-600 hover:text-gray-900"}`}
            >
              {TL[t]} 
              {grade && grade.percentage > 0 && (
                <span className={`text-xs px-2 py-0.5 rounded ${GRADE_COLORS[grade.grade]}`}>
                  {grade.grade}
                </span>
              )}
            </button>
          );
        })}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 mb-6">
        {ATYPES.map(type => {
          const a = getAsmt(type);
          if (!a) return null;
          const isEditing = editId === a.id;
          const p = pct(a.score, a.max);
          return (
            <div key={type} className="bg-white rounded-2xl border border-gray-200 p-5 group hover:shadow-md transition-all">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2 text-gray-500">
                  {typeIcons[type]}
                  <span className="text-xs font-bold uppercase">{AL[type]}</span>
                </div>
                <span className={`text-xs font-bold px-2.5 py-1 rounded-full ${p >= 80 ? "bg-emerald-50 text-emerald-700" : p >= 60 ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}>
                  {gradeStr(a.score, a.max)}
                </span>
              </div>
              {isEditing ? (
                <div className="flex items-center gap-2 mb-3">
                  <input
                    type="number"
                    min={0}
                    max={a.max}
                    value={editVal}
                    onChange={(e) => setEditVal(e.target.value)}
                    onKeyDown={(e) => { if (e.key === "Enter") commitEdit(a); if (e.key === "Escape") setEditId(null); }}
                    className="w-20 border border-gray-200 rounded-lg px-3 py-1.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500"
                    autoFocus
                  />
                  <span className="text-sm text-gray-500">/ {a.max}</span>
                  <button onClick={() => commitEdit(a)} className="p-1.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
                    <Check size={14} />
                  </button>
                  <button onClick={() => setEditId(null)} className="p-1.5 hover:bg-gray-100 rounded-lg transition-colors">
                    <X size={14} />
                  </button>
                </div>
              ) : (
                <div className="flex items-end gap-2 mb-3">
                  <span className="text-3xl font-bold font-mono leading-none">{a.score}</span>
                  <span className="text-sm text-gray-500 mb-0.5">/ {a.max}</span>
                  <span className={`ml-auto text-sm font-mono px-2.5 py-0.5 rounded ${badgeCls(a.score, a.max)}`}>{p}%</span>
                  <button
                    onClick={() => { setEditId(a.id); setEditVal(String(a.score)); }}
                    className="p-1 hover:bg-gray-100 rounded opacity-0 group-hover:opacity-100 transition-all"
                  >
                    <Pencil size={14} />
                  </button>
                </div>
              )}
              <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                <div className={`h-full rounded-full transition-all duration-500 ${barCls(a.score, a.max)}`} style={{ width: `${p}%` }} />
              </div>
            </div>
          );
        })}
      </div>

      <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-sm">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-4 gap-2">
          <h3 className="font-bold text-gray-900">{TL[term]} Summary</h3>
          {termAvg !== null && (
            <span className={`text-sm font-bold px-4 py-1.5 rounded-full ${termAvg >= 80 ? "bg-emerald-50 text-emerald-700" : termAvg >= 60 ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}>
              Term Average: {termAvg}%
            </span>
          )}
        </div>
        <div className="grid grid-cols-3 md:grid-cols-5 gap-3">
          {ATYPES.map(type => {
            const a = getAsmt(type);
            if (!a) return null;
            return (
              <div key={type} className="text-center py-3 bg-gray-50 rounded-xl">
                <div className="text-lg font-bold font-mono">{gradeStr(a.score, a.max)}</div>
                <div className="text-xs text-gray-500 mt-0.5 hidden md:block">{AL[type]}</div>
                <div className="text-sm font-mono text-gray-500">{pct(a.score, a.max)}%</div>
              </div>
            );
          })}
        </div>
      </div>

      {showEditProfile && <EditProfileModal student={student} onSave={onUpdateStudent} onClose={() => setShowEditProfile(false)} />}
    </div>
  );
}

function DocsView({ docs, schools, klasses, onAdd, onUpdate, onDelete }: { docs: Doc[]; schools: School[]; klasses: Klass[]; onAdd: () => void; onUpdate: (id: string, content: string) => void; onDelete: (id: string) => void }) {
  const [selected, setSelected] = useState<Doc | null>(null);
  const [editing, setEditing] = useState(false);
  const [editContent, setEditContent] = useState("");
  const [fSchool, setFSchool] = useState("");
  const [fTerm, setFTerm] = useState("");
  const [fType, setFType] = useState("");
  const [isMobile, setIsMobile] = useState(window.innerWidth < 768);

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 768);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const filtered = docs.filter(d => 
    (!fSchool || d.schoolId === fSchool) && 
    (!fTerm || d.term === Number(fTerm)) && 
    (!fType || d.type === fType)
  );
  const schoolName = (id: string) => schools.find(s => s.id === id)?.name ?? id;
  const klassName = (id: string | null) => id ? klasses.find(k => k.id === id)?.name : null;

  const saveEdit = () => { 
    if (selected) { 
      onUpdate(selected.id, editContent); 
      setSelected({ ...selected, content: editContent }); 
    } 
    setEditing(false); 
  };
  
  const typeBadge = (t: AType) => {
    const map = {
      test1: "bg-blue-50 text-blue-700",
      test2: "bg-blue-50 text-blue-700",
      test3: "bg-blue-50 text-blue-700",
      project: "bg-purple-50 text-purple-700",
      exam: "bg-emerald-50 text-emerald-700"
    };
    return map[t];
  };

  if (isMobile) {
    return (
      <div className="flex flex-col h-full">
        <div className="p-4 border-b border-gray-200 bg-white flex-shrink-0">
          <div className="flex items-center justify-between mb-4">
            <h2 className="font-bold text-lg text-gray-900">Documents</h2>
            <button onClick={onAdd} className="flex items-center gap-1.5 bg-blue-600 text-white px-4 py-2 rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors">
              <Plus size={16} /> New
            </button>
          </div>
          <div className="space-y-2">
            <select value={fSchool} onChange={e => setFSchool(e.target.value)} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500">
              <option value="">All Schools</option>
              {schools.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
            <div className="grid grid-cols-2 gap-2">
              <select value={fTerm} onChange={e => setFTerm(e.target.value)} className="border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500">
                <option value="">All Terms</option>
                <option value="1">First Term</option>
                <option value="2">Second Term</option>
                <option value="3">Third Term</option>
              </select>
              <select value={fType} onChange={e => setFType(e.target.value)} className="border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500">
                <option value="">All Types</option>
                {ATYPES.map(t => <option key={t} value={t}>{AL[t]}</option>)}
              </select>
            </div>
          </div>
        </div>
        <div className="flex-1 overflow-y-auto p-4 space-y-3 bg-gray-50">
          {filtered.length === 0 ? (
            <div className="text-center py-16 text-gray-500">
              <FileText size={40} className="mx-auto mb-3 text-gray-300" />
              <p className="font-medium">No documents found</p>
            </div>
          ) : (
            filtered.map(doc => (
              <div key={doc.id} className="bg-white rounded-xl border border-gray-200 p-4 hover:shadow-md transition-all">
                <div className="flex items-start justify-between">
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-gray-900 truncate">{doc.title}</h3>
                    <p className="text-sm text-gray-500 truncate">{schoolName(doc.schoolId)}</p>
                    <div className="flex flex-wrap gap-1.5 mt-2">
                      <span className="text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full">{TL[doc.term]}</span>
                      <span className={`text-xs px-2 py-0.5 rounded-full ${typeBadge(doc.type)}`}>{AL[doc.type]}</span>
                    </div>
                  </div>
                  <button onClick={() => { setSelected(doc); setEditing(false); }} className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg ml-2">
                    <ExternalLink size={18} />
                  </button>
                </div>
              </div>
            ))
          )}
        </div>
        {selected && (
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-end sm:items-center justify-center p-4">
            <div className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] flex flex-col animate-in slide-in-from-bottom duration-300">
              <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 flex-shrink-0">
                <h3 className="font-bold text-lg text-gray-900 truncate">{selected.title}</h3>
                <button onClick={() => setSelected(null)} className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                  <X size={20} />
                </button>
              </div>
              <div className="flex-1 overflow-y-auto p-6">
                {editing ? (
                  <textarea
                    value={editContent}
                    onChange={(e) => setEditContent(e.target.value)}
                    className="w-full h-full min-h-[300px] font-mono text-sm border border-gray-200 rounded-xl p-4 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white leading-relaxed"
                  />
                ) : (
                  <pre className="font-mono text-sm leading-relaxed whitespace-pre-wrap text-gray-800 bg-gray-50 rounded-xl p-4 min-h-[300px] border border-gray-200">
                    {selected.content}
                  </pre>
                )}
              </div>
              <div className="flex flex-wrap gap-2 px-6 py-4 border-t border-gray-100 flex-shrink-0">
                {editing ? (
                  <>
                    <button onClick={() => setEditing(false)} className="flex items-center gap-1.5 border border-gray-200 px-4 py-2 rounded-xl text-sm font-medium hover:bg-gray-50 transition-colors">
                      <X size={16} /> Cancel
                    </button>
                    <button onClick={saveEdit} className="flex items-center gap-1.5 bg-blue-600 text-white px-4 py-2 rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors">
                      <Save size={16} /> Save
                    </button>
                  </>
                ) : (
                  <>
                    <button onClick={() => { setEditing(true); setEditContent(selected.content); }} className="flex items-center gap-1.5 border border-gray-200 px-4 py-2 rounded-xl text-sm font-medium hover:bg-gray-50 transition-colors">
                      <Pencil size={16} /> Edit
                    </button>
                    <button onClick={() => dlDoc(selected)} className="flex items-center gap-1.5 border border-gray-200 px-4 py-2 rounded-xl text-sm font-medium hover:bg-gray-50 transition-colors">
                      <Download size={16} /> Download
                    </button>
                    <button onClick={() => { onDelete(selected.id); setSelected(null); }} className="flex items-center gap-1.5 border border-red-200 text-red-600 px-4 py-2 rounded-xl text-sm font-medium hover:bg-red-50 transition-colors">
                      <Trash2 size={16} /> Delete
                    </button>
                  </>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="flex w-full h-full bg-gray-50">
      <div className="w-80 border-r border-gray-200 flex flex-col flex-shrink-0 bg-white">
        <div className="p-6 border-b border-gray-200">
          <div className="flex items-center justify-between mb-4">
            <h2 className="font-bold text-lg text-gray-900">Documents</h2>
            <button onClick={onAdd} className="flex items-center gap-1.5 bg-blue-600 text-white px-4 py-2 rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors shadow-sm">
              <Plus size={16} /> New
            </button>
          </div>
          <div className="space-y-2">
            <select value={fSchool} onChange={e => setFSchool(e.target.value)} className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500">
              <option value="">All Schools</option>
              {schools.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
            <div className="grid grid-cols-2 gap-2">
              <select value={fTerm} onChange={e => setFTerm(e.target.value)} className="border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500">
                <option value="">All Terms</option>
                <option value="1">First Term</option>
                <option value="2">Second Term</option>
                <option value="3">Third Term</option>
              </select>
              <select value={fType} onChange={e => setFType(e.target.value)} className="border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-blue-500">
                <option value="">All Types</option>
                {ATYPES.map(t => <option key={t} value={t}>{AL[t]}</option>)}
              </select>
            </div>
          </div>
        </div>
        <div className="overflow-y-auto flex-1">
          {filtered.length === 0 ? (
            <div className="p-6 text-center text-gray-500">
              <FileText size={32} className="mx-auto mb-2 text-gray-300" />
              <p className="text-sm">No documents found</p>
            </div>
          ) : (
            <div className="divide-y divide-gray-100">
              {filtered.map(doc => (
                <button
                  key={doc.id}
                  onClick={() => { setSelected(doc); setEditing(false); }}
                  className={`w-full text-left px-6 py-4 hover:bg-gray-50 transition-colors ${selected?.id === doc.id ? "bg-blue-50 border-r-2 border-blue-600" : ""}`}
                >
                  <div className="flex items-start gap-3">
                    <FileText size={16} className="mt-0.5 flex-shrink-0 text-gray-400" />
                    <div className="min-w-0">
                      <p className="text-sm font-semibold text-gray-900 line-clamp-2">{doc.title}</p>
                      <p className="text-sm text-gray-500 mt-0.5 truncate">{schoolName(doc.schoolId)}</p>
                      <div className="flex gap-1.5 mt-2 flex-wrap">
                        <span className="text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full font-medium">{TL[doc.term]}</span>
                        <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${typeBadge(doc.type)}`}>{AL[doc.type]}</span>
                      </div>
                    </div>
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>
      </div>

      <div className="flex-1 flex flex-col min-w-0 bg-white overflow-hidden">
        {selected ? (
          <>
            <div className="px-6 py-4 border-b border-gray-200 bg-white flex items-start justify-between gap-4 flex-shrink-0 flex-wrap">
              <div className="min-w-0">
                <h2 className="font-bold text-lg text-gray-900 truncate">{selected.title}</h2>
                <div className="flex items-center gap-3 mt-1 flex-wrap">
                  <span className="text-sm text-gray-500">{schoolName(selected.schoolId)}</span>
                  {klassName(selected.classId) && <span className="text-sm text-gray-500">{klassName(selected.classId)}</span>}
                  <span className="text-sm text-gray-500">{TL[selected.term]}</span>
                  <span className={`text-xs px-2.5 py-0.5 rounded-full font-medium ${typeBadge(selected.type)}`}>{AL[selected.type]}</span>
                  <span className="text-sm text-gray-400 font-mono">{selected.createdAt}</span>
                </div>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0 flex-wrap">
                {editing ? (
                  <>
                    <button onClick={() => setEditing(false)} className="flex items-center gap-1.5 border border-gray-200 px-3 py-1.5 rounded-xl text-sm font-medium hover:bg-gray-50 transition-colors">
                      <X size={14} /> Cancel
                    </button>
                    <button onClick={saveEdit} className="flex items-center gap-1.5 bg-blue-600 text-white px-3 py-1.5 rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors">
                      <Save size={14} /> Save
                    </button>
                  </>
                ) : (
                  <>
                    <button onClick={() => { setEditing(true); setEditContent(selected.content); }} className="flex items-center gap-1.5 border border-gray-200 px-3 py-1.5 rounded-xl text-sm font-medium hover:bg-gray-50 transition-colors">
                      <Pencil size={14} /> Edit
                    </button>
                    <button onClick={() => dlDoc(selected)} className="flex items-center gap-1.5 border border-gray-200 px-3 py-1.5 rounded-xl text-sm font-medium hover:bg-gray-50 transition-colors">
                      <Download size={14} /> Download
                    </button>
                    <button onClick={() => { onDelete(selected.id); setSelected(null); }} className="flex items-center gap-1.5 border border-red-200 text-red-600 px-3 py-1.5 rounded-xl text-sm font-medium hover:bg-red-50 transition-colors">
                      <Trash2 size={14} /> Delete
                    </button>
                  </>
                )}
              </div>
            </div>
            <div className="flex-1 p-6 overflow-y-auto bg-gray-50">
              {editing ? (
                <textarea
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  className="w-full h-full min-h-[500px] font-mono text-sm border border-gray-200 rounded-xl p-5 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white leading-relaxed resize-none"
                />
              ) : (
                <pre className="font-mono text-sm leading-relaxed whitespace-pre-wrap text-gray-800 bg-white rounded-xl p-6 min-h-[500px] border border-gray-200 shadow-sm">
                  {selected.content}
                </pre>
              )}
            </div>
          </>
        ) : (
          <div className="flex-1 flex items-center justify-center text-gray-500 flex-col gap-4">
            <FileText size={56} className="text-gray-300" />
            <p className="text-lg font-medium">Select a document to view or edit</p>
            <p className="text-sm text-gray-400">Or create a new document</p>
          </div>
        )}
      </div>
    </div>
  );
}

// ── Main App ──────────────────────────────────────────────────────────────────
export default function App() {
  const [view, setView] = useState<View>("schools");
  const [school, setSchool] = useState<School | null>(null);
  const [klass, setKlass] = useState<Klass | null>(null);
  const [student, setStudent] = useState<Student | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isOnline, setIsOnline] = useState(isSupabaseAvailable());

  const [schools, setSchools] = useState<School[]>([]);
  const [klasses, setKlasses] = useState<Klass[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [asmts, setAsmts] = useState<Asmt[]>([]);
  const [docs, setDocs] = useState<Doc[]>([]);

  const [showAddSchool, setShowAddSchool] = useState(false);
  const [showAddClass, setShowAddClass] = useState(false);
  const [showAddStudent, setShowAddStudent] = useState(false);
  const [showAddDoc, setShowAddDoc] = useState(false);

  // ── Load Data ──────────────────────────────────────────────────────────────
  const loadData = useCallback(async () => {
    setLoading(true);
    setError(null);
    
    if (!isSupabaseAvailable()) {
      setError('Cannot connect to database. Please check your connection.');
      setLoading(false);
      setIsOnline(false);
      return;
    }

    try {
      setIsOnline(true);
      
      const [schoolsRes, classesRes, studentsRes, assessmentsRes, docsRes] = await Promise.all([
        supabase!.from('schools').select('*').order('name'),
        supabase!.from('classes').select('*').order('name'),
        supabase!.from('students').select('*').order('last_name'),
        supabase!.from('assessments').select('*'),
        supabase!.from('documents').select('*').order('created_at', { ascending: false }),
      ]);

      if (schoolsRes.error) throw new Error(schoolsRes.error.message);
      if (classesRes.error) throw new Error(classesRes.error.message);
      if (studentsRes.error) throw new Error(studentsRes.error.message);
      if (assessmentsRes.error) throw new Error(assessmentsRes.error.message);
      if (docsRes.error) throw new Error(docsRes.error.message);

      setSchools(schoolsRes.data || []);
      setKlasses(classesRes.data || []);
      setStudents(studentsRes.data || []);
      setAsmts(assessmentsRes.data || []);
      setDocs(docsRes.data || []);
      
      console.log('✅ Data loaded successfully!');
    } catch (err: any) {
      console.error('❌ Error loading data:', err);
      setError(`Failed to load data: ${err.message}`);
    } finally {
      setLoading(false);
    }
  }, []);

  // ── Real-time Subscriptions ──────────────────────────────────────────────
  useEffect(() => {
    loadData();

    if (!isSupabaseAvailable()) return;

    const channels = [
      supabase!.channel('schools_changes')
        .on('postgres_changes', { event: '*', schema: 'public', table: 'schools' }, loadData)
        .subscribe(),
      supabase!.channel('classes_changes')
        .on('postgres_changes', { event: '*', schema: 'public', table: 'classes' }, loadData)
        .subscribe(),
      supabase!.channel('students_changes')
        .on('postgres_changes', { event: '*', schema: 'public', table: 'students' }, loadData)
        .subscribe(),
      supabase!.channel('assessments_changes')
        .on('postgres_changes', { event: '*', schema: 'public', table: 'assessments' }, loadData)
        .subscribe(),
      supabase!.channel('documents_changes')
        .on('postgres_changes', { event: '*', schema: 'public', table: 'documents' }, loadData)
        .subscribe(),
    ];

    const interval = setInterval(() => {
      setIsOnline(isSupabaseAvailable());
    }, 30000);

    return () => {
      channels.forEach(ch => ch.unsubscribe());
      clearInterval(interval);
    };
  }, [loadData]);

  // ── CRUD Operations ──────────────────────────────────────────────────────

  const addSchool = async (newSchool: School) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot save: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('schools').insert([newSchool]);
      if (error) throw error;
    } catch (err: any) {
      console.error('Error adding school:', err);
      setError(`Failed to save school: ${err.message}`);
    }
  };

  const delSchool = async (id: string) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot delete: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('schools').delete().eq('id', id);
      if (error) throw error;
    } catch (err: any) {
      console.error('Error deleting school:', err);
      setError(`Failed to delete school: ${err.message}`);
    }
  };

  const addKlass = async (newKlass: Klass) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot save: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('classes').insert([newKlass]);
      if (error) throw error;
    } catch (err: any) {
      console.error('Error adding class:', err);
      setError(`Failed to save class: ${err.message}`);
    }
  };

  const delKlass = async (id: string) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot delete: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('classes').delete().eq('id', id);
      if (error) throw error;
    } catch (err: any) {
      console.error('Error deleting class:', err);
      setError(`Failed to delete class: ${err.message}`);
    }
  };

  const addStudent = async (newStudent: Student) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot save: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('students').insert([newStudent]);
      if (error) throw error;

      // Create assessments for the new student
      const year = klasses.find(k => k.id === newStudent.classId)?.academicYear || CURRENT_YEAR;
      const newAsmts: Asmt[] = [];
      for (const term of [1, 2, 3] as Term[])
        for (const type of ATYPES)
          newAsmts.push({ id: uid(), studentId: newStudent.id, term, type, score: 0, max: AMAX[type], year });
      
      const { error: asmtError } = await supabase!.from('assessments').insert(newAsmts);
      if (asmtError) throw asmtError;
    } catch (err: any) {
      console.error('Error adding student:', err);
      setError(`Failed to save student: ${err.message}`);
    }
  };

  const delStudent = async (id: string) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot delete: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('students').delete().eq('id', id);
      if (error) throw error;
    } catch (err: any) {
      console.error('Error deleting student:', err);
      setError(`Failed to delete student: ${err.message}`);
    }
  };

  const updateStudent = async (updated: Student) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot update: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('students').update(updated).eq('id', updated.id);
      if (error) throw error;
    } catch (err: any) {
      console.error('Error updating student:', err);
      setError(`Failed to update student: ${err.message}`);
    }
  };

  const updateScore = async (id: string, score: number) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot update: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('assessments').update({ score }).eq('id', id);
      if (error) throw error;
    } catch (err: any) {
      console.error('Error updating score:', err);
      setError(`Failed to update score: ${err.message}`);
    }
  };

  const addDoc = async (newDoc: Doc) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot save: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('documents').insert([newDoc]);
      if (error) throw error;
    } catch (err: any) {
      console.error('Error adding document:', err);
      setError(`Failed to save document: ${err.message}`);
    }
  };

  const updateDoc = async (id: string, content: string) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot update: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('documents').update({ content }).eq('id', id);
      if (error) throw error;
    } catch (err: any) {
      console.error('Error updating document:', err);
      setError(`Failed to update document: ${err.message}`);
    }
  };

  const delDoc = async (id: string) => {
    if (!isSupabaseAvailable()) {
      setError('Cannot delete: Database not available');
      return;
    }
    try {
      const { error } = await supabase!.from('documents').delete().eq('id', id);
      if (error) throw error;
    } catch (err: any) {
      console.error('Error deleting document:', err);
      setError(`Failed to delete document: ${err.message}`);
    }
  };

  // ── Navigation ──────────────────────────────────────────────────────────────
  const goSchools = () => { setView("schools"); setSchool(null); setKlass(null); setStudent(null); };
  const goClasses = (s: School) => { setSchool(s); setKlass(null); setStudent(null); setView("classes"); };
  const goStudents = (k: Klass) => { setKlass(k); setStudent(null); setView("students"); };
  const goStudent = (s: Student) => { setStudent(s); setView("student"); };
  const goDocs = () => setView("docs");

  const schoolKlasses = klasses.filter(k => k.schoolId === school?.id);
  const klassStudents = students.filter(s => s.classId === klass?.id);
  const studentAsmts = asmts.filter(a => a.studentId === student?.id);

  // ── Loading State ──────────────────────────────────────────────────────────
  if (loading) {
    return (
      <div className="flex h-screen bg-gray-50 items-center justify-center">
        <div className="text-center">
          <Loader2 size={48} className="animate-spin text-blue-600 mx-auto mb-4" />
          <p className="text-gray-600 font-medium">Loading data...</p>
          <p className="text-sm text-gray-400 mt-1">Connecting to database</p>
        </div>
      </div>
    );
  }

  // ── Error State ─────────────────────────────────────────────────────────────
  if (error && error.includes('Cannot connect')) {
    return (
      <div className="flex h-screen bg-gray-50 items-center justify-center">
        <div className="text-center max-w-md p-8 bg-white rounded-2xl shadow-lg">
          <WifiOff size={56} className="text-red-500 mx-auto mb-4" />
          <h2 className="text-xl font-bold text-gray-900 mb-2">Connection Error</h2>
          <p className="text-gray-600 mb-6">{error}</p>
          <button onClick={loadData} className="flex items-center gap-2 bg-blue-600 text-white px-6 py-2.5 rounded-xl font-semibold hover:bg-blue-700 transition-colors mx-auto">
            <RefreshCw size={18} /> Retry
          </button>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex h-screen bg-gray-50 items-center justify-center">
        <div className="text-center max-w-md p-8 bg-white rounded-2xl shadow-lg">
          <AlertCircle size={56} className="text-red-500 mx-auto mb-4" />
          <h2 className="text-xl font-bold text-gray-900 mb-2">Error</h2>
          <p className="text-gray-600 mb-6">{error}</p>
          <button onClick={loadData} className="flex items-center gap-2 bg-blue-600 text-white px-6 py-2.5 rounded-xl font-semibold hover:bg-blue-700 transition-colors mx-auto">
            <RefreshCw size={18} /> Retry
          </button>
        </div>
      </div>
    );
  }

  // ── Render ──────────────────────────────────────────────────────────────────
  return (
    <div className="flex h-screen bg-gray-50 overflow-hidden">
      {/* Connection Status Bar */}
      <div className={`fixed top-0 left-0 right-0 z-50 px-4 py-1.5 text-xs text-center font-medium ${isOnline ? 'bg-emerald-50 text-emerald-700 border-b border-emerald-200' : 'bg-amber-50 text-amber-700 border-b border-amber-200'}`}>
        {isOnline ? (
          <span className="flex items-center justify-center gap-2">
            <Wifi size={12} /> Connected to Database | Real-time updates active
          </span>
        ) : (
          <span className="flex items-center justify-center gap-2">
            <WifiOff size={12} /> Offline - Changes will be saved when connection is restored
          </span>
        )}
      </div>

      {/* Sidebar */}
      <aside className="w-64 bg-white border-r border-gray-200 flex flex-col flex-shrink-0 shadow-sm hidden md:flex mt-8">
        <div className="px-6 py-5 border-b border-gray-200">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center shadow-sm">
              <GraduationCap size={20} className="text-white" />
            </div>
            <div>
              <span className="text-gray-900 font-bold text-lg tracking-tight">SchoolTrack</span>
              <div className="text-gray-400 text-xs font-medium">Academic Manager</div>
            </div>
          </div>
        </div>

        <nav className="flex-1 p-4 space-y-1 overflow-y-auto">
          <p className="text-gray-400 text-xs font-bold uppercase tracking-wider px-3 mb-3">Navigation</p>
          <button
            onClick={goSchools}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm font-medium transition-all ${view !== "docs" ? "bg-blue-50 text-blue-700" : "text-gray-600 hover:bg-gray-50"}`}
          >
            <Building2 size={18} />
            Schools
          </button>
          <button
            onClick={goDocs}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm font-medium transition-all ${view === "docs" ? "bg-blue-50 text-blue-700" : "text-gray-600 hover:bg-gray-50"}`}
          >
            <FileText size={18} />
            Documents
          </button>
        </nav>

        <div className="p-4 border-t border-gray-200 space-y-2">
          <div className="flex items-center justify-between text-sm">
            <span className="text-gray-500">Schools</span>
            <span className="font-bold text-gray-900">{schools.length}</span>
          </div>
          <div className="flex items-center justify-between text-sm">
            <span className="text-gray-500">Classes</span>
            <span className="font-bold text-gray-900">{klasses.length}</span>
          </div>
          <div className="flex items-center justify-between text-sm">
            <span className="text-gray-500">Students</span>
            <span className="font-bold text-gray-900">{students.length}</span>
          </div>
          <div className="flex items-center justify-between text-sm pt-2 border-t border-gray-100">
            <span className="text-gray-500">Status</span>
            <span className={`text-xs font-medium ${isOnline ? 'text-emerald-600' : 'text-amber-600'}`}>
              {isOnline ? '🟢 Online' : '🟡 Offline'}
            </span>
          </div>
        </div>
      </aside>

      {/* Mobile Bottom Navigation */}
      <nav className="md:hidden fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 z-50 flex justify-around py-3">
        <button
          onClick={goSchools}
          className={`flex flex-col items-center gap-1 px-4 py-1 rounded-lg text-xs font-medium ${view !== "docs" ? "text-blue-600" : "text-gray-500"}`}
        >
          <Building2 size={22} />
          <span>Schools</span>
        </button>
        <button
          onClick={goDocs}
          className={`flex flex-col items-center gap-1 px-4 py-1 rounded-lg text-xs font-medium ${view === "docs" ? "text-blue-600" : "text-gray-500"}`}
        >
          <FileText size={22} />
          <span>Docs</span>
        </button>
      </nav>

      {/* Main content */}
      <main className="flex-1 flex flex-col overflow-hidden min-w-0 pb-16 md:pb-0 mt-8">
        {view === "docs" ? (
          <DocsView
            docs={docs}
            schools={schools}
            klasses={klasses}
            onAdd={() => setShowAddDoc(true)}
            onUpdate={updateDoc}
            onDelete={delDoc}
          />
        ) : (
          <div className="flex-1 overflow-y-auto">
            {view === "schools" && (
              <SchoolsView
                schools={schools}
                onOpen={goClasses}
                onAdd={() => setShowAddSchool(true)}
                onDelete={delSchool}
              />
            )}
            {view === "classes" && school && (
              <ClassesView
                school={school}
                klasses={schoolKlasses}
                students={students}
                onOpen={goStudents}
                onAdd={() => setShowAddClass(true)}
                onBack={goSchools}
                onDelete={delKlass}
              />
            )}
            {view === "students" && school && klass && (
              <StudentsView
                school={school}
                klass={klass}
                students={klassStudents}
                asmts={asmts}
                onOpen={goStudent}
                onAdd={() => setShowAddStudent(true)}
                onBack={() => goClasses(school)}
                onBackSchool={goSchools}
                onDelete={delStudent}
              />
            )}
            {view === "student" && school && klass && student && (
              <StudentDetailView
                school={school}
                klass={klass}
                student={student}
                asmts={studentAsmts}
                onUpdateScore={updateScore}
                onBack={() => goStudents(klass)}
                onBackClass={() => goClasses(school)}
                onBackSchool={goSchools}
                onUpdateStudent={updateStudent}
              />
            )}
          </div>
        )}
      </main>

      {/* Modals */}
      {showAddSchool && <AddSchoolModal onSave={addSchool} onClose={() => setShowAddSchool(false)} />}
      {showAddClass && school && <AddClassModal schoolId={school.id} onSave={addKlass} onClose={() => setShowAddClass(false)} />}
      {showAddStudent && klass && <AddStudentModal classId={klass.id} onSave={addStudent} onClose={() => setShowAddStudent(false)} />}
      {showAddDoc && <AddDocModal schools={schools} klasses={klasses} onSave={addDoc} onClose={() => setShowAddDoc(false)} />}
    </div>
  );
}
